openapi: 3.0.0
info:
  title: 'HivePress REST API'
  version: '1.0'
servers:
  -
    url: /wp-json/hivepress/v1
    description: ''
paths:
  '/listings/{listing_id}':
    post:
      tags:
        - Listings
      summary: 'Update a listing'
      parameters:
        -
          $ref: '#/components/parameters/listing_id'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Listing'
      responses:
        '200':
          description: OK
  '/listings/{listing_id}/hide':
    post:
      tags:
        - Listings
      summary: 'Hide or unhide a listing'
      parameters:
        -
          $ref: '#/components/parameters/listing_id'
      responses:
        '200':
          description: OK
components:
  schemas:
    Listing:
      description: ''
      properties:
        title:
          description: 'Listing title.'
          type: string
        description:
          description: 'Listing description.'
          type: string
      type: object
  parameters:
    listing_id:
      name: listing_id
      in: path
      description: 'Listing ID.'
      required: true
      schema:
        type: integer
