openapi: 3.0.0
info:
  title: 'My First API'
  description: 'Abstract controller.'
  version: '1.0'
paths:
  '/listings/{listing_id}':
    post:
      responses:
        '200':
          description: 'Updates listing'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Listing'
  '/listings/{listing_id}/hide':
    post:
      responses:
        '200':
          description: 'Hide listing'
components:
  schemas:
    Listing:
      description: Listing.
      properties:
        '':
          description: 'The product name,'
          type: string
      type: object
