openapi: 3.0.0
info:
  title: 'HivePress REST API'
  version: '1.0'
servers:
  -
    url: /wp-json/hivepress/v1
paths:
  '/listings/{listing_id}/hide':
    post:
      tags:
        - Listings
      summary: 'Hide or unhide a listing'
      parameters:
        -
          $ref: '#/components/parameters/listing_id'
      responses:
        '200':
          description: OK
components:
  schemas:
    Listing:
      description: ''
      properties:
        title:
          description: Title
          type: string
        description:
          description: Description
          type: string
      type: object
  parameters:
    listing_id:
      name: listing_id
      in: path
      description: 'The listing ID'
      required: true
      schema:
        type: integer
