name: Update REST API

on:
  push:
    branches:
      - develop

  workflow_dispatch:

jobs:
  update-api-reference:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          tools: composer

      - name: Install Swagger
        run: composer require zircote/swagger-php

      - name: Generate OpenAPI
        run: vendor/bin/openapi . -e vendor -o openapi.yaml -l

      - name: Deploy documentation
        uses: bump-sh/github-action@v1
        with:
          doc: rest-api
          token: ${{ secrets.BUMP_TOKEN }}
          file: openapi.yaml
