name: Update REST API

on:
  push:
    branches:
      - develop

  workflow_dispatch:

jobs:
  update-api-reference:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: bump-sh/github-action@v1
        with:
          doc: rest-api
          token: ${{ secrets.BUMP_TOKEN }}
          file: ./openapi.yml
