name: Update REST API

on:
  push:
    branches:
      - develop

  workflow_dispatch:

jobs:
  update-api-reference:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate OpenAPI
        run: |
          composer global require zircote/swagger-php
          openapi . -e vendor -o openapi.yaml -l

      - uses: bump-sh/github-action@v1
        with:
          doc: rest-api
          token: ${{ secrets.BUMP_TOKEN }}
          file: openapi.yaml
